# ========================================================
# Tetris Deployment
# Manages the pod lifecycle for the game application
# ========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris  # Unique identifier for this deployment

spec:
  replicas: 1  # Run exactly one instance of the game pod

  selector:  # Links the deployment to pods with these labels
    matchLabels:
      app: tetris

  template:  # Blueprint for creating new pods
    metadata:
      labels:
        app: tetris  # Must match selector.matchLabels

    spec:
      nodeSelector:  # Constrains pods to nodes with this label
        nodegroup: game-nodes

      containers:
        - name: tetris  # Container name (visible in logs/dashboard)
          image: 824622998597.dkr.ecr.us-east-2.amazonaws.com/games:tetris-rc1  # ECR image location
          ports:
            - containerPort: 8000  # The port the game server listens on

---
# ========================================================
# Tetris Service
# Provides stable network access to the game pods
# ========================================================
apiVersion: v1
kind: Service
metadata:
  name: tetris-service  # DNS name for internal cluster access

spec:
  selector:  # Routes traffic to pods with this label
    app: tetris

  ports:
    - protocol: TCP  # Standard protocol for HTTP traffic
      port: 80  # External service port
      targetPort: 8000  # Forwards to container's port 8000

---
# ========================================================
# Tetris Ingress
# Manages external HTTP access to the service
# ========================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetris-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/permanent-redirect: /games/tetris/
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Redirect /games/tetris → /games/tetris/
          - path: /games/tetris
            pathType: Exact
            backend:
              service:
                name: tetris-service
                port:
                  number: 80

          # Route /games/tetris/ and everything under it
          - path: /games/tetris/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tetris-service
                port:
                  number: 80
